// ============================================================
// カテゴリー色の定義（好きな色を指定）
// ============================================================
var catColors = {
  "特別来賓":         "#FF0000",
  "自治体首長・議長":  "#DA9694",
  "天草市議会":        "#F2F2F2",
  "その他来賓":        "#FFFF00",
  "被表彰者":          "#FFCCFF",
  "被表彰者（登壇者）":  "#FF6699",
  "報道関係者":          "#8e44ad",
  "地区振興会長、区長":   "#b7dee8",
  "部長、支所長":        "#538dd5",
  "支所職員":            "#538dd5",
  "随行者":            "#E26B0A",
  "天草市":            "#A6A6A6",
  "警察":              "#000000"
  // ★ カテゴリーが増えたらここに追加するだけ ★
};
// ============================================================
// 名簿データ（このファイルだけ差し替えれば更新完了）
// ============================================================
const guests = [
{no:304, cat:"天草市", org:"天草市", title:"教育長", name:"平田　浩一", kana:"ヒラタ", seat:"3列-1"},
{no:51, cat:"天草市議会", org:"天草市議会", title:"議長", name:"若山　敬介", kana:"ワカヤマ", seat:"3列-3"},
{no:302, cat:"天草市", org:"天草市", title:"副市長", name:"野崎　真司", kana:"ノザキ", seat:"3列-2"},
{no:301, cat:"天草市", org:"天草市", title:"市長", name:"馬場　昭治", kana:"ババ", seat:"3列-4"},
{no:306, cat:"警察", org:"", title:"", name:"警察", kana:"ケイサツ", seat:"3列-5"},
{no:307, cat:"警察", org:"", title:"", name:"警察", kana:"ケイサツ", seat:"3列-6"},
{no:10, cat:"特別来賓", org:"熊本県議会", title:"議員", name:"山口　裕", kana:"ヤマグチ", seat:"3列-7"},
{no:9, cat:"特別来賓", org:"熊本県議会", title:"議員", name:"楠本　千秋", kana:"クスモト", seat:"3列-8"},
{no:8, cat:"特別来賓", org:"熊本県議会", title:"議員", name:"池田　和貴", kana:"イケダ", seat:"3列-9"},
{no:7, cat:"特別来賓", org:"熊本県知事代理", title:"天草広域本部本部長", name:"浦田　美紀", kana:"ウラタ", seat:"3列-10"},
{no:2, cat:"特別来賓", org:"", title:"衆議院議員", name:"吉田　宣弘", kana:"ヨシダ", seat:"3列-11"},
{no:1, cat:"特別来賓", org:"国土交通大臣", title:"衆議院議員", name:"金子　恭之", kana:"カネコ", seat:"3列-12"},
{no:3, cat:"特別来賓", org:"", title:"参議院議員", name:"馬場　成志", kana:"ババ", seat:"3列-13"},
{no:4, cat:"特別来賓", org:"", title:"参議院議員", name:"本田　顕子", kana:"ホンダ", seat:"3列-14"},
{no:5, cat:"特別来賓", org:"", title:"参議院議員", name:"犬童　周作", kana:"インドウ", seat:"3列-15"},
{no:6, cat:"特別来賓", org:"", title:"参議院議員松村祥史代理　秘書長", name:"畑山　登", kana:"ハタヤマ", seat:"3列-16"},
{no:308, cat:"警察", org:"", title:"", name:"警察", kana:"ケイサツ", seat:"3列-17"},
{no:309, cat:"警察", org:"", title:"", name:"警察", kana:"ケイサツ", seat:"3列-18"},
{no:20, cat:"自治体首長・議長", org:"上天草市", title:"市長", name:"堀江　隆臣", kana:"ホリエ", seat:"3列-19"},
{no:26, cat:"自治体首長・議長", org:"苓北町", title:"町長", name:"山﨑　秀典", kana:"ヤマサキ", seat:"3列-20"},
{no:11, cat:"自治体首長・議長", org:"熊本市", title:"副市長", name:"岡田　芳和", kana:"オカダ", seat:"3列-21"},
{no:12, cat:"自治体首長・議長", org:"八代市", title:"副市長", name:"平井　宏英", kana:"ヒライ", seat:"3列-22"},
{no:13, cat:"自治体首長・議長", org:"人吉市", title:"市長", name:"松岡　隼人", kana:"マツオカ", seat:"3列-23"},
{no:14, cat:"自治体首長・議長", org:"荒尾市", title:"副市長", name:"石川　陽一", kana:"イシカワ", seat:"3列-24"},
{no:15, cat:"自治体首長・議長", org:"水俣市", title:"総務企画部長", name:"梅下　俊克", kana:"ウメシタ", seat:"3列-25"},
{no:56, cat:"天草市議会", org:"天草市議会", title:"議員", name:"宮下　幸一郎", kana:"ミヤシタ", seat:"4列-1"},
{no:55, cat:"天草市議会", org:"天草市議会", title:"議員", name:"中尾　友二", kana:"ナカオ", seat:"4列-2"},
{no:54, cat:"天草市議会", org:"天草市議会", title:"議員", name:"勝木　幸生", kana:"カツキ", seat:"4列-3"},
{no:53, cat:"天草市議会", org:"天草市議会", title:"議員", name:"浜崎　昭臣", kana:"ハマサキ", seat:"4列-4"},
{no:52, cat:"天草市議会", org:"天草市議会", title:"副議長", name:"小川　圭三", kana:"オガワ", seat:"4列-5"},
{no:305, cat:"天草市", org:"天草市", title:"病院事業管理者", name:"竹中　賢治", kana:"タケナカ", seat:"4列-6"},
{no:35, cat:"自治体首長・議長", org:"荒尾市議会", title:"議長", name:"浜崎　英利", kana:"ハマサキ", seat:"4列-7"},
{no:34, cat:"自治体首長・議長", org:"人吉市議会", title:"議長", name:"宮原　将志", kana:"ミヤハラ", seat:"4列-8"},
{no:33, cat:"自治体首長・議長", org:"八代市議会", title:"議長", name:"髙山　正夫", kana:"タカヤマ", seat:"4列-9"},
{no:32, cat:"自治体首長・議長", org:"熊本市議会", title:"副議長", name:"井本　正広", kana:"イモト", seat:"4列-10"},
{no:46, cat:"自治体首長・議長", org:"苓北町議会", title:"議長", name:"野﨑　幸洋", kana:"ノザキ", seat:"4列-11"},
{no:41, cat:"自治体首長・議長", org:"上天草市議会", title:"議長", name:"嶋元　秀司", kana:"シマモト", seat:"4列-12"},
{no:310, cat:"警察", org:"", title:"", name:"警察", kana:"ケイサツ", seat:"4列-13"},
{no:16, cat:"自治体首長・議長", org:"玉名市", title:"副市長", name:"吉田　勇人", kana:"ヨシダ", seat:"4列-14"},
{no:17, cat:"自治体首長・議長", org:"山鹿市", title:"副市長", name:"阿蘇品　貴司", kana:"アソシナ", seat:"4列-15"},
{no:18, cat:"自治体首長・議長", org:"菊池市", title:"副市長", name:"藤井　一恵", kana:"フジイ", seat:"4列-16"},
{no:19, cat:"自治体首長・議長", org:"宇土市", title:"市長", name:"光井　正吾", kana:"ミツイ", seat:"4列-17"},
{no:21, cat:"自治体首長・議長", org:"宇城市", title:"副市長", name:"田村　真一", kana:"タムラ", seat:"4列-18"},
{no:22, cat:"自治体首長・議長", org:"阿蘇市", title:"副市長", name:"沖　圭一郎", kana:"オキ", seat:"4列-19"},
{no:23, cat:"自治体首長・議長", org:"合志市", title:"政策監", name:"吉村　幸一", kana:"ヨシムラ", seat:"4列-20"},
{no:24, cat:"自治体首長・議長", org:"産山村", title:"村長", name:"井　雄一郎", kana:"イ", seat:"4列-21"},
{no:25, cat:"自治体首長・議長", org:"高森町", title:"町長", name:"草村　大成", kana:"クサムラ", seat:"4列-22"},
{no:27, cat:"自治体首長・議長", org:"浦河町", title:"町長", name:"松田　有宏", kana:"マツダ", seat:"4列-23"},
{no:28, cat:"自治体首長・議長", org:"瀬戸市", title:"副市長", name:"大森　雅之", kana:"オオモリ", seat:"4列-24"},
{no:29, cat:"自治体首長・議長", org:"南島原市", title:"副市長", name:"宮﨑　太", kana:"ミヤザキ", seat:"4列-25"},
{no:30, cat:"自治体首長・議長", org:"出水市", title:"市長", name:"椎木　伸一", kana:"シイキ", seat:"4列-26"},
{no:31, cat:"自治体首長・議長", org:"長島町", title:"総務課長", name:"町口　真浩", kana:"マチグチ", seat:"4列-27"},
{no:64, cat:"天草市議会", org:"天草市議会", title:"議員", name:"蓑田　庸子", kana:"ミノダ", seat:"5列-1"},
{no:63, cat:"天草市議会", org:"天草市議会", title:"議員", name:"藤﨑　正博", kana:"フジサキ", seat:"5列-2"},
{no:62, cat:"天草市議会", org:"天草市議会", title:"議員", name:"澤井　一富", kana:"サワイ", seat:"5列-3"},
{no:61, cat:"天草市議会", org:"天草市議会", title:"議員", name:"門口　徹", kana:"カドグチ", seat:"5列-4"},
{no:60, cat:"天草市議会", org:"天草市議会", title:"議員", name:"五嶋　善彦", kana:"ゴトウ", seat:"5列-5"},
{no:59, cat:"天草市議会", org:"天草市議会", title:"議員", name:"五通　俊作", kana:"ゴツウ", seat:"5列-6"},
{no:58, cat:"天草市議会", org:"天草市議会", title:"議員", name:"柴田　誠", kana:"シバタ", seat:"5列-7"},
{no:57, cat:"天草市議会", org:"天草市議会", title:"議員", name:"濱洲　大心", kana:"ハマス", seat:"5列-8"},
{no:50, cat:"自治体首長・議長", org:"出水市議会", title:"議長", name:"北御門　伸彦", kana:"キタミカド", seat:"5列-9"},
{no:49, cat:"自治体首長・議長", org:"雲仙市議会", title:"議長", name:"大久保　正美", kana:"オオクボ", seat:"5列-10"},
{no:48, cat:"自治体首長・議長", org:"瀬戸市議会", title:"議長", name:"髙島　淳", kana:"タカシマ", seat:"5列-11"},
{no:47, cat:"自治体首長・議長", org:"浦河町議会", title:"議長", name:"米谷　友光", kana:"ヨネタニ", seat:"5列-12"},
{no:45, cat:"自治体首長・議長", org:"高森町議会", title:"議長", name:"牛嶋　津世志", kana:"ウシジマ", seat:"5列-13"},
{no:44, cat:"自治体首長・議長", org:"産山村議会", title:"議長", name:"西澤　正", kana:"ニシザワ", seat:"5列-14"},
{no:43, cat:"自治体首長・議長", org:"阿蘇市議会", title:"副議長", name:"谷﨑　利浩", kana:"タニザキ", seat:"5列-15"},
{no:42, cat:"自治体首長・議長", org:"宇城市議会", title:"議長", name:"豊田　紀代美", kana:"トヨダ", seat:"5列-16"},
{no:40, cat:"自治体首長・議長", org:"宇土市議会", title:"議長", name:"野口　修一", kana:"ノグチ", seat:"5列-17"},
{no:39, cat:"自治体首長・議長", org:"菊池市議会", title:"副議長", name:"泉田　栄一朗", kana:"イズミダ", seat:"5列-18"},
{no:38, cat:"自治体首長・議長", org:"山鹿市議会", title:"議長", name:"有働　辰喜", kana:"ウドウ", seat:"5列-19"},
{no:37, cat:"自治体首長・議長", org:"玉名市議会", title:"議長", name:"西川　裕文", kana:"ニシカワ", seat:"5列-20"},
{no:36, cat:"自治体首長・議長", org:"水俣市議会", title:"副議長", name:"田口　憲雄", kana:"タグチ", seat:"5列-21"},
{no:75, cat:"天草市議会", org:"", title:"前天草市議会議員", name:"平山　泰司", kana:"ヒラヤマ", seat:"6列-1"},
{no:74, cat:"天草市議会", org:"天草市議会", title:"議員", name:"植田　貴俊", kana:"ウエダ", seat:"6列-2"},
{no:73, cat:"天草市議会", org:"天草市議会", title:"議員", name:"金子　馨", kana:"カネコ", seat:"6列-3"},
{no:72, cat:"天草市議会", org:"天草市議会", title:"議員", name:"生嶋　祥子", kana:"イクシマ", seat:"6列-4"},
{no:71, cat:"天草市議会", org:"天草市議会", title:"議員", name:"吉田　修", kana:"ヨシダ", seat:"6列-5"},
{no:70, cat:"天草市議会", org:"天草市議会", title:"議員", name:"栁田　光芳", kana:"ヤナギダ", seat:"6列-6"},
{no:69, cat:"天草市議会", org:"天草市議会", title:"議員", name:"赤城　史浩", kana:"アカギ", seat:"6列-7"},
{no:68, cat:"天草市議会", org:"天草市議会", title:"議員", name:"竹本　亨", kana:"タケモト", seat:"6列-8"},
{no:67, cat:"天草市議会", org:"天草市議会", title:"議員", name:"浦本　力", kana:"ウラモト", seat:"6列-9"},
{no:66, cat:"天草市議会", org:"天草市議会", title:"議員", name:"松岡　寿", kana:"マツオカ", seat:"6列-10"},
{no:65, cat:"天草市議会", org:"天草市議会", title:"議員", name:"鯖江　達朗", kana:"サバエ", seat:"6列-11"},
{no:119, cat:"その他来賓", org:"天草市民生委員児童委員協議会連合会", title:"会長", name:"濱田　幸人", kana:"ハマダ", seat:"6列-12"},
{no:120, cat:"その他来賓", org:"社会福祉法人天草市社会福祉協議会", title:"事務局長", name:"小浦　良介", kana:"コウラ", seat:"6列-13"},
{no:110, cat:"その他来賓", org:"日本年金機構本渡年金事務所", title:"所長", name:"長谷川　健一", kana:"ハセガワ", seat:"6列-14"},
{no:118, cat:"その他来賓", org:"熊本県市町村職員年金者連盟天草支部", title:"支部長", name:"冨安　英猛", kana:"トミヤス", seat:"6列-15"},
{no:103, cat:"その他来賓", org:"天草教育事務所", title:"主幹兼指導課長", name:"中村　富男", kana:"ナカムラ", seat:"6列-16"},
{no:104, cat:"その他来賓", org:"天草税務署", title:"署長", name:"永﨑　政継", kana:"ナガサキ", seat:"6列-17"},
{no:108, cat:"その他来賓", org:"天草海上保安署", title:"署長", name:"金棒　康彦", kana:"カナボウ", seat:"6列-18"},
{no:109, cat:"その他来賓", org:"厚生労働省熊本労働局天草労働基準監督署", title:"署長", name:"嘉悦　正人", kana:"カエツ", seat:"6列-19"},
{no:107, cat:"その他来賓", org:"天草広域連合消防本部", title:"消防長", name:"戸村　羊士", kana:"トムラ", seat:"6列-20"},
{no:179, cat:"その他来賓", org:"本渡商工会議所", title:"会頭", name:"金子　勉", kana:"カネコ", seat:"6列-21"},
{no:180, cat:"その他来賓", org:"牛深商工会議所", title:"会頭", name:"益田　政昭", kana:"マスダ", seat:"6列-22"},
{no:181, cat:"その他来賓", org:"天草市商工会", title:"会長", name:"古賀　源一郎", kana:"コガ", seat:"6列-23"},
{no:111, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"池崎　教授", kana:"イケザキ", seat:"7列-1"},
{no:112, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"行合　八恵子", kana:"ユキアイ", seat:"7列-2"},
{no:113, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"木下　えり子", kana:"キノシタ", seat:"7列-3"},
{no:114, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"小林　景子", kana:"コバヤシ", seat:"7列-4"},
{no:117, cat:"その他来賓", org:"天草市監査委員", title:"", name:"福岡　耕二", kana:"フクオカ", seat:"7列-5"},
{no:116, cat:"その他来賓", org:"天草市監査委員", title:"", name:"富田　善三郎", kana:"トミタ", seat:"7列-6"},
{no:81, cat:"その他来賓", org:"", title:"前天草市教育長", name:"石井　二三男", kana:"イシイ", seat:"7列-7"},
{no:80, cat:"その他来賓", org:"", title:"前天草市副市長", name:"金子　邦彦", kana:"カネコ", seat:"7列-8"},
{no:79, cat:"天草市議会", org:"", title:"前天草市議会議員", name:"前田　正之", kana:"マエダ", seat:"7列-9"},
{no:78, cat:"天草市議会", org:"", title:"前天草市議会議員", name:"下田　昇一郎", kana:"シモダ", seat:"7列-10"},
{no:77, cat:"天草市議会", org:"", title:"前天草市議会議員", name:"鶴戸　継啓", kana:"ツルド", seat:"7列-11"},
{no:76, cat:"天草市議会", org:"", title:"前天草市議会議員", name:"船辺　修", kana:"フナベ", seat:"7列-12"},
{no:126, cat:"その他来賓", org:"天草市老人クラブ連合会", title:"会長", name:"早水　英雄", kana:"ハヤミズ", seat:"7列-13"},
{no:127, cat:"その他来賓", org:"公益社団法人天草市シルバー人材センター", title:"理事長", name:"江﨑　和男", kana:"エザキ", seat:"7列-14"},
{no:182, cat:"その他来賓", org:"公益社団法人天草法人会", title:"会長", name:"永田　章一", kana:"ナガタ", seat:"7列-15"},
{no:149, cat:"その他来賓", org:"天草経済開発同友会", title:"会長", name:"野上　俊樹", kana:"ノガミ", seat:"7列-16"},
{no:133, cat:"その他来賓", org:"あまくさ農業協同組合", title:"代表理事組合長", name:"﨑本　和人", kana:"サキモト", seat:"7列-17"},
{no:134, cat:"その他来賓", org:"本渡五和農業協同組合", title:"代表理事組合長", name:"吉田　誠", kana:"ヨシダ", seat:"7列-18"},
{no:135, cat:"その他来賓", org:"熊本県畜産農業協同組合天草支所", title:"運営委員長", name:"千原　勝也", kana:"チハラ", seat:"7列-19"},
{no:136, cat:"その他来賓", org:"熊本県農業共済組合天草支所", title:"支所長", name:"宮崎　浩司", kana:"ミヤザキ", seat:"7列-20"},
{no:137, cat:"その他来賓", org:"地方卸売市場本渡青果事業協同組合", title:"理事長", name:"濱　三千秀", kana:"ハマ", seat:"7列-21"},
{no:138, cat:"その他来賓", org:"天草地域森林組合", title:"代表理事専務", name:"野嶋　義澄", kana:"ノジマ", seat:"7列-22"},
{no:139, cat:"その他来賓", org:"天草漁業協同組合", title:"副組合長理事", name:"渕口　文俊", kana:"フチグチ", seat:"7列-23"},
{no:140, cat:"その他来賓", org:"熊本県海水養殖漁業協同組合", title:"代表理事組合長", name:"深川　英穂", kana:"フカガワ", seat:"7列-24"},
{no:100, cat:"その他来賓", org:"", title:"天草市農業委員会会長", name:"山下　和弘", kana:"ヤマシタ", seat:"8列-1"},
{no:115, cat:"その他来賓", org:"天草市選挙管理委員会", title:"委員長", name:"岡部　義夫", kana:"オカベ", seat:"8列-2"},
{no:178, cat:"その他来賓", org:"天草市消防団", title:"団長", name:"田中　浩介", kana:"タナカ", seat:"8列-3"},
{no:168, cat:"その他来賓", org:"熊本検察審査協会天草支部", title:"支部長", name:"落合　正実", kana:"オチアイ", seat:"8列-4"},
{no:89, cat:"その他来賓", org:"河浦まちづくり協議会", title:"会長", name:"野中　幸廣", kana:"ノナカ", seat:"8列-5"},
{no:88, cat:"その他来賓", org:"天草まちづくり協議会", title:"会長", name:"嶋田　順一", kana:"シマダ", seat:"8列-6"},
{no:87, cat:"その他来賓", org:"五和まちづくり協議会", title:"会長", name:"井下　克也", kana:"イノシタ", seat:"8列-7"},
{no:86, cat:"その他来賓", org:"栖本まちづくり協議会", title:"会長", name:"倉田　千尋", kana:"クラタ", seat:"8列-8"},
{no:85, cat:"その他来賓", org:"倉岳まちづくり協議会", title:"会長", name:"稲津　千明", kana:"イナヅ", seat:"8列-9"},
{no:84, cat:"その他来賓", org:"御所浦まちづくり協議会", title:"会長", name:"森　啓輔", kana:"モリ", seat:"8列-10"},
{no:83, cat:"その他来賓", org:"牛深まちづくり協議会", title:"会長", name:"舩場　みちな", kana:"フナバ", seat:"8列-11"},
{no:82, cat:"その他来賓", org:"本渡まちづくり協議会", title:"会長", name:"中川　竹治", kana:"ナカガワ", seat:"8列-12"},
{no:125, cat:"その他来賓", org:"天草市保育所連盟", title:"会長", name:"安田　量寛", kana:"ヤスダ", seat:"8列-13"},
{no:128, cat:"その他来賓", org:"一般社団法人天草郡市医師会", title:"会長", name:"東　一成", kana:"ヒガシ", seat:"8列-14"},
{no:188, cat:"その他来賓", org:"天草本渡ライオンズクラブ", title:"会長", name:"岩﨑　東洋司", kana:"イワサキ", seat:"8列-15"},
{no:187, cat:"その他来賓", org:"牛深ロータリークラブ", title:"会長", name:"山下　修平", kana:"ヤマシタ", seat:"8列-16"},
{no:186, cat:"その他来賓", org:"天草中央ロータリークラブ", title:"会長", name:"山川　悟", kana:"ヤマカワ", seat:"8列-17"},
{no:185, cat:"その他来賓", org:"天草ロータリークラブ", title:"会長", name:"小島　竜二", kana:"コジマ", seat:"8列-18"},
{no:184, cat:"その他来賓", org:"天草食品衛生協会", title:"会長", name:"堀田　征夫", kana:"ホッタ", seat:"8列-19"},
{no:183, cat:"その他来賓", org:"一般社団法人天草本渡青年会議所", title:"理事長", name:"大中　龍", kana:"オオナカ", seat:"8列-20"},
{no:141, cat:"その他来賓", org:"熊本大分真珠養殖漁業協同組合", title:"代表理事組合長", name:"田畑　圭規", kana:"タバタ", seat:"8列-21"},
{no:142, cat:"その他来賓", org:"倉岳町漁業協同組合", title:"代表理事組合長", name:"蛭子本　臣偵", kana:"エビスモト", seat:"8列-22"},
{no:143, cat:"その他来賓", org:"御所浦町漁業協同組合", title:"代表理事組合長", name:"脇島　成郎", kana:"ワキシマ", seat:"8列-23"},
{no:144, cat:"その他来賓", org:"栖本漁業協同組合", title:"代表理事組合長", name:"倉本　雄市", kana:"クラモト", seat:"8列-24"},
{no:148, cat:"その他来賓", org:"天草市建友会", title:"副会長", name:"福富　崇司", kana:"フクトミ", seat:"9列-1"},
{no:146, cat:"その他来賓", org:"一般社団法人熊本県天草地区建設業協会", title:"理事長", name:"松下　眞一", kana:"マツシタ", seat:"9列-2"},
{no:147, cat:"その他来賓", org:"熊本県建築士会天草支部", title:"副支部長", name:"池崎　正志", kana:"イケザキ", seat:"9列-3"},
{no:177, cat:"その他来賓", org:"牛深警察署沿岸警備協力会", title:"会長", name:"杦本　幸徳", kana:"スギモト", seat:"9列-4"},
{no:176, cat:"その他来賓", org:"天草警察署沿岸警備協力会", title:"会長", name:"北　武敏", kana:"キタ", seat:"9列-5"},
{no:175, cat:"その他来賓", org:"牛深地区安全運転管理者等協議会", title:"会長", name:"福岡　英人", kana:"フクオカ", seat:"9列-6"},
{no:174, cat:"その他来賓", org:"天草市交通指導員会", title:"隊長", name:"尾下　明", kana:"オシタ", seat:"9列-7"},
{no:173, cat:"その他来賓", org:"牛深地区交通安全協会", title:"会長", name:"中村　富人", kana:"ナカムラ", seat:"9列-8"},
{no:172, cat:"その他来賓", org:"天草地区交通安全協会", title:"会長", name:"田中　靖士", kana:"タナカ", seat:"9列-9"},
{no:171, cat:"その他来賓", org:"天草市自衛隊家族会", title:"会長", name:"若山　幸信", kana:"ワカヤマ", seat:"9列-10"},
{no:170, cat:"その他来賓", org:"天草地区保護司会", title:"会長", name:"出田　豪", kana:"イズタ", seat:"9列-11"},
{no:169, cat:"その他来賓", org:"天草人権擁護委員協議会", title:"会長", name:"貴田　英広", kana:"キダ", seat:"9列-12"},
{no:131, cat:"その他来賓", org:"子宝島あまくさ助産師会", title:"会長", name:"池田　眞智子", kana:"イケダ", seat:"9列-13"},
{no:129, cat:"その他来賓", org:"一般社団法人天草郡市薬剤師会", title:"副会長", name:"草積　里恵子", kana:"クサヅミ", seat:"9列-14"},
{no:130, cat:"その他来賓", org:"熊本県獣医師会天草支部", title:"支部長", name:"奈良﨑　孝一郎", kana:"ナラザキ", seat:"9列-15"},
{no:121, cat:"その他来賓", org:"天草市身体障害者福祉協議会", title:"会長", name:"松本　若津", kana:"マツモト", seat:"9列-16"},
{no:122, cat:"その他来賓", org:"天草市視力障害者福祉協会", title:"会長", name:"大塚　聖子", kana:"オオツカ", seat:"9列-17"},
{no:123, cat:"その他来賓", org:"白い雲の会", title:"会長", name:"堤田　照一", kana:"ツツミダ", seat:"9列-20"},
{no:124, cat:"その他来賓", org:"精神保健福祉会天草地域家族会", title:"事務局長", name:"池崎　宏一", kana:"イケザキ", seat:"9列-21"},
{no:145, cat:"その他来賓", org:"天草たばこ販売協同組合", title:"理事", name:"山川　智己", kana:"ヤマカワ", seat:"9列-22"},
{no:189, cat:"その他来賓", org:"ゼロ―ム天草", title:"新事業推進委員長", name:"木原　潤", kana:"キハラ", seat:"9列-23"},
{no:190, cat:"その他来賓", org:"天草エアライン株式会社", title:"代表取締役社長", name:"山西　聡", kana:"ヤマニシ", seat:"9列-24"},
{no:157, cat:"その他来賓", org:"天草女将の会", title:"", name:"松本　鈴子", kana:"マツモト　スズコ", seat:"10列-1"},
{no:154, cat:"その他来賓", org:"有明町旅館組合", title:"組合長", name:"松本　國雄", kana:"マツモト　クニオ", seat:"10列-2"},
{no:155, cat:"その他来賓", org:"下田温泉旅館組合", title:"組合長", name:"藤本　貴士", kana:"フジモト　タカシ", seat:"10列-3"},
{no:153, cat:"その他来賓", org:"天草ほんど観光旅館ホテル組合", title:"組合長", name:"横島　龍一", kana:"ヨコシマ　リュウイチ", seat:"10列-4"},
{no:152, cat:"その他来賓", org:"天草市社交飲食業組合", title:"組合長", name:"石井　美恵", kana:"イシイ　ミエ", seat:"10列-5"},
{no:151, cat:"その他来賓", org:"本渡飲食業組合", title:"組合長", name:"田口　博典", kana:"タグチ　ヒロノリ", seat:"10列-6"},
{no:150, cat:"その他来賓", org:"一般社団法人天草宝島観光協会", title:"会長", name:"山下　修平", kana:"ヤマシタ", seat:"10列-7"},
{no:167, cat:"その他来賓", org:"一般社団法人天草市芸術文化協会", title:"会長", name:"江﨑　俊一", kana:"エサキ", seat:"10列-8"},
{no:166, cat:"その他来賓", org:"天草文化協会", title:"副会長", name:"嶺　力", kana:"ミネ", seat:"10列-9"},
{no:165, cat:"その他来賓", org:"天草市スポーツ推進委員協議会", title:"会長", name:"渡邊　亨", kana:"ワタナベ", seat:"10列-10"},
{no:164, cat:"その他来賓", org:"一般社団法人天草市スポーツ協会", title:"会長", name:"江浦　むつえ", kana:"エウラ", seat:"10列-11"},
{no:163, cat:"その他来賓", org:"一般社団法人　市民活動サポートあまみん", title:"代表理事", name:"山本　智保子", kana:"ヤマモト", seat:"10列-12"},
{no:162, cat:"その他来賓", org:"天草市男女共同参画推進ネットワーク　つんのでネット～風～", title:"事務局", name:"益田　靖子", kana:"マスダ", seat:"10列-13"},
{no:160, cat:"その他来賓", org:"天草市地域婦人会連絡協議会", title:"会長", name:"木崎　眞美子", kana:"キザキ　マミコ", seat:"10列-14"},
{no:132, cat:"その他来賓", org:"天草市食生活改善推進員協議会", title:"会長", name:"風間　泰民子", kana:"カザマ", seat:"10列-15"},
{no:161, cat:"その他来賓", org:"天草市子ども会育成連絡協議会", title:"会長", name:"島﨑　太", kana:"シマザキ", seat:"10列-16"},
{no:159, cat:"その他来賓", org:"天草市ＰＴＡ連絡協議会", title:"会長", name:"松本　大器", kana:"マツモト　ダイキ", seat:"10列-17"},
{no:158, cat:"その他来賓", org:"天草市小中学校長会", title:"会長", name:"松原　康近", kana:"マツバラ　ヤスチカ", seat:"10列-18"},
{no:102, cat:"その他来賓", org:"天草ケーブルネットワーク株式会社", title:"代表取締役", name:"西村　正治", kana:"ニシムラ", seat:"10列-19"},
{no:101, cat:"その他来賓", org:"株式会社熊本県民テレビ天草通信部", title:"", name:"有江　武利", kana:"アリエ", seat:"10列-20"},



 // --- 被表彰者 E-22～E-30 ---
  {no:1, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-22"},
  {no:2, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-23"},
  {no:3, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-24"},
  {no:4, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-25"},
  {no:5, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-26"},
  {no:6, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-27"},
  {no:7, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-28"},
  {no:8, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-29"},
  {no:9, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"5列-30"},
  // --- 被表彰者 F-24～F-34 ---
  {no:10, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-24"},
  {no:11, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-25"},
  {no:12, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-26"},
  {no:13, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-27"},
  {no:14, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-28"},
  {no:15, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-29"},
  {no:16, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-30"},
  {no:17, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-31"},
  {no:18, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-32"},
  {no:19, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-33"},
  {no:20, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"6列-34"},
  // --- 被表彰者 G-25～G-36 ---
  {no:21, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-25"},
  {no:22, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-26"},
  {no:23, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-27"},
  {no:24, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-28"},
  {no:25, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-29"},
  {no:26, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-30"},
  {no:27, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-31"},
  {no:28, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-32"},
  {no:29, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-33"},
  {no:30, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-34"},
  {no:31, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-35"},
  {no:32, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"7列-36"},
  // --- 被表彰者 H-25～H-32 ---
  {no:33, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-25"},
  {no:34, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-26"},
  {no:35, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-27"},
  {no:36, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-28"},
  {no:37, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-29"},
  {no:38, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-30"},
  {no:39, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-31"},
  {no:40, cat:"被表彰者", org:"", title:"", name:"", kana:"", seat:"8列-32"},
  // --- 被表彰者（登壇者）H-33～H-36 ---
  {no:41, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"8列-33"},
  {no:42, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"8列-34"},
  {no:43, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"8列-35"},
  {no:44, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"8列-36"},
  // --- 被表彰者（登壇者）I-25～I-36 ---
  {no:45, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-25"},
  {no:46, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-26"},
  {no:47, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-27"},
  {no:48, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-28"},
  {no:49, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-29"},
  {no:50, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-30"},
  {no:51, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-31"},
  {no:52, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-32"},
  {no:53, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-33"},
  {no:54, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-34"},
  {no:55, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-35"},
  {no:56, cat:"被表彰者（登壇者）", org:"", title:"", name:"", kana:"", seat:"9列-36"},
  // --- 報道関係者 J-22～J-27 ---
  {no:57, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-21"},
  {no:57, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-22"},
  {no:58, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-23"},
  {no:59, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-24"},
  {no:60, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-25"},
  {no:61, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-26"},
  {no:62, cat:"報道関係者", org:"", title:"", name:"", kana:"", seat:"10列-27"},
  // --- 地区振興会長、区長 K-1～K-27 ---
  {no:63, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-1"},
  {no:64, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-2"},
  {no:65, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-3"},
  {no:66, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-4"},
  {no:67, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-5"},
  {no:68, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-6"},
  {no:69, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-7"},
  {no:70, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-8"},
  {no:71, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-9"},
  {no:72, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-10"},
  {no:73, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-11"},
  {no:74, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-12"},
  {no:75, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-13"},
  {no:76, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-14"},
  {no:77, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-15"},
  {no:78, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-16"},
  {no:79, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-17"},
  {no:80, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-18"},
  {no:81, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-19"},
  {no:82, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-20"},
  {no:83, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-21"},
  {no:84, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-22"},
  {no:85, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-23"},
  {no:86, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-24"},
  {no:87, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-25"},
  {no:88, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-26"},
  {no:89, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"11列-27"},
  // --- 地区振興会長、区長 L-1～L-27 ---
  {no:90, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-1"},
  {no:91, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-2"},
  {no:92, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-3"},
  {no:93, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-4"},
  {no:94, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-5"},
  {no:95, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-6"},
  {no:96, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-7"},
  {no:97, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-8"},
  {no:98, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-9"},
  {no:99, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-10"},
  {no:100, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-11"},
  {no:101, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-12"},
  {no:102, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-13"},
  {no:103, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-14"},
  {no:104, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-15"},
  {no:105, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-16"},
  {no:106, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-17"},
  {no:107, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-18"},
  {no:108, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-19"},
  {no:109, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-20"},
  {no:110, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-21"},
  {no:111, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-22"},
  {no:112, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-23"},
  {no:113, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-24"},
  {no:114, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-25"},
  {no:115, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-26"},
  {no:116, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"12列-27"},
  // --- 地区振興会長、区長 M-7～M-33 ---
  {no:117, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-7"},
  {no:118, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-8"},
  {no:119, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-9"},
  {no:120, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-10"},
  {no:121, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-11"},
  {no:122, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-12"},
  {no:123, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-13"},
  {no:124, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-14"},
  {no:125, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-15"},
  {no:126, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-16"},
  {no:127, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-17"},
  {no:128, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-18"},
  {no:129, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-19"},
  {no:130, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-20"},
  {no:131, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-21"},
  {no:132, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-22"},
  {no:133, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-23"},
  {no:134, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-24"},
  {no:135, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-25"},
  {no:136, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-26"},
  {no:137, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-27"},
  {no:138, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-28"},
  {no:139, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-29"},
  {no:140, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-30"},
  {no:141, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-31"},
  {no:142, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-32"},
  {no:143, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"13列-33"},
  // --- 地区振興会長、区長 N-7～N-33 ---
  {no:144, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-7"},
  {no:145, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-8"},
  {no:146, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-9"},
  {no:147, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-10"},
  {no:148, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-11"},
  {no:149, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-12"},
  {no:150, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-13"},
  {no:151, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-14"},
  {no:152, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-15"},
  {no:153, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-16"},
  {no:154, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-17"},
  {no:155, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-18"},
  {no:156, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-19"},
  {no:157, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-20"},
  {no:158, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-21"},
  {no:159, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-22"},
  {no:160, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-23"},
  {no:161, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-24"},
  {no:162, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-25"},
  {no:163, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-26"},
  {no:164, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-27"},
  {no:165, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-28"},
  {no:166, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-29"},
  {no:167, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-30"},
  {no:168, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-31"},
  {no:169, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-32"},
  {no:170, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"14列-33"},
  // --- 地区振興会長、区長 O-7～O-33 ---
  {no:171, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-7"},
  {no:172, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-8"},
  {no:173, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-9"},
  {no:174, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-10"},
  {no:175, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-11"},
  {no:176, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-12"},
  {no:177, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-13"},
  {no:178, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-14"},
  {no:179, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-15"},
  {no:180, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-16"},
  {no:181, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-17"},
  {no:182, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-18"},
  {no:183, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-19"},
  {no:184, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-20"},
  {no:185, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-21"},
  {no:186, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-22"},
  {no:187, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-23"},
  {no:188, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-24"},
  {no:189, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-25"},
  {no:190, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-26"},
  {no:191, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-27"},
  {no:192, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-28"},
  {no:193, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-29"},
  {no:194, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-30"},
  {no:195, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-31"},
  {no:196, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-32"},
  {no:197, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"15列-33"},
  // --- 地区振興会長、区長 P-7～P-33 ---
  {no:198, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-7"},
  {no:199, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-8"},
  {no:200, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-9"},
  {no:201, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-10"},
  {no:202, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-11"},
  {no:203, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-12"},
  {no:204, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-13"},
  {no:205, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-14"},
  {no:206, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-15"},
  {no:207, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-16"},
  {no:208, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-17"},
  {no:209, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-18"},
  {no:210, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-19"},
  {no:211, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-20"},
  {no:212, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-21"},
  {no:213, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-22"},
  {no:214, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-23"},
  {no:215, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-24"},
  {no:216, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-25"},
  {no:217, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-26"},
  {no:218, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-27"},
  {no:219, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-28"},
  {no:220, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-29"},
  {no:221, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-30"},
  {no:222, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-31"},
  {no:223, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-32"},
  {no:224, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"16列-33"},
  // --- 地区振興会長、区長 Q-8～Q-20 ---
  {no:225, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-8"},
  {no:226, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-9"},
  {no:227, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-10"},
  {no:228, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-11"},
  {no:229, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-12"},
  {no:230, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-13"},
  {no:231, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-14"},
  {no:232, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-15"},
  {no:233, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-16"},
  {no:234, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-17"},
  {no:235, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-18"},
  {no:236, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-19"},
  {no:237, cat:"地区振興会長、区長", org:"", title:"", name:"", kana:"", seat:"17列-20"},
  // --- 部長、支所長 M-1～M-6 ---
  {no:238, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-1"},
  {no:239, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-2"},
  {no:240, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-3"},
  {no:241, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-4"},
  {no:242, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-5"},
  {no:243, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"13列-6"},
  // --- 部長、支所長 N-1～N-6 ---
  {no:244, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-1"},
  {no:245, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-2"},
  {no:246, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-3"},
  {no:247, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-4"},
  {no:248, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-5"},
  {no:249, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"14列-6"},
  // --- 部長、支所長 O-1～O-6 ---
  {no:250, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-1"},
  {no:251, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-2"},
  {no:252, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-3"},
  {no:253, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-4"},
  {no:254, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-5"},
  {no:255, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"15列-6"},
  // --- 部長、支所長 P-1～P-6 ---
  {no:256, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-1"},
  {no:257, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-2"},
  {no:258, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-3"},
  {no:259, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-4"},
  {no:260, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-5"},
  {no:261, cat:"部長、支所長", org:"", title:"", name:"", kana:"", seat:"16列-6"},
  // --- 支所職員 Q-1～Q-7 ---
  {no:262, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-1"},
  {no:263, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-2"},
  {no:264, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-3"},
  {no:265, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-4"},
  {no:266, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-5"},
  {no:267, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-6"},
  {no:268, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"17列-7"},
  // --- 支所職員 N-34～N-36 ---
  {no:269, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"14列-34"},
  {no:270, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"14列-35"},
  {no:271, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"14列-36"},
  // --- 支所職員 O-34～O-36 ---
  {no:272, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"15列-34"},
  {no:273, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"15列-35"},
  {no:274, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"15列-36"},
  // --- 支所職員 P-34～P-36 ---
  {no:275, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"16列-34"},
  {no:276, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"16列-35"},
  {no:277, cat:"支所職員", org:"", title:"", name:"", kana:"", seat:"16列-36"},
  // --- 随行席 Q-25～Q-36 ---
  {no:278, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-25"},
  {no:279, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-26"},
  {no:280, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-27"},
  {no:281, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-28"},
  {no:282, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-29"},
  {no:283, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-30"},
  {no:284, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-31"},
  {no:285, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-32"},
  {no:286, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-33"},
  {no:287, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-34"},
  {no:288, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-35"},
  {no:289, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"17列-36"},
  // --- 随行席 R-25～R-36 ---
  {no:290, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-25"},
  {no:291, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-26"},
  {no:292, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-27"},
  {no:293, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-28"},
  {no:294, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-29"},
  {no:295, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-30"},
  {no:296, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-31"},
  {no:297, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-32"},
  {no:298, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-33"},
  {no:299, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-34"},
  {no:300, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-35"},
  {no:301, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"18列-36"},
  // --- 随行席 S-25～S-36 ---
  {no:302, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-25"},
  {no:303, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-26"},
  {no:304, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-27"},
  {no:305, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-28"},
  {no:306, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-29"},
  {no:307, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-30"},
  {no:308, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-31"},
  {no:309, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-32"},
  {no:310, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-33"},
  {no:311, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-34"},
  {no:312, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-35"},
  {no:313, cat:"随行席", org:"", title:"", name:"", kana:"", seat:"19列-36"}
];
