// ============================================================
// カテゴリー色の定義（好きな色を指定）
// ============================================================
var catColors = {
  "特別来賓":         "#FF0000",
  "自治体首長・議長":  "#DA9694",
  "天草市議会":        "#F2F2F2",
  "その他来賓":        "#FFFF00",
  "被表彰者":          "#FFCCFF",
  "被表彰者（登壇者）":  "#FF6699",
  "報道関係者":          "#8e44ad",
  "地区振興会長、区長":   "#b7dee8",
  "部長、支所長":        "#538dd5",
  "支所職員":            "#538dd5",
  "随行者":            "#E26B0A"
  // ★ カテゴリーが増えたらここに追加するだけ ★
};
// ============================================================
// 名簿データ（このファイルだけ差し替えれば更新完了）
// ============================================================
const guests = [
{no:1, cat:"特別来賓", org:"国土交通大臣", title:"衆議院議員", name:"金子　恭之", kana:"カネコ", seat:"C-12"},
{no:2, cat:"特別来賓", org:"", title:"衆議院議員", name:"吉田　宣弘", kana:"ヨシダ", seat:"C-11"},
{no:3, cat:"特別来賓", org:"", title:"参議院議員", name:"馬場　成志", kana:"ババ", seat:"C-13"},
{no:4, cat:"特別来賓", org:"", title:"参議院議員", name:"本田　顕子", kana:"ホンダ", seat:"C-14"},
{no:5, cat:"特別来賓", org:"", title:"参議院議員", name:"犬童　周作", kana:"インドウ", seat:"C-15"},
{no:6, cat:"特別来賓", org:"", title:"参議院議員松村祥史代理　秘書長", name:"畑山　登", kana:"ハタヤマ", seat:"C-16"},
{no:7, cat:"特別来賓", org:"", title:"熊本県知事代理　天草広域本部本部長", name:"浦田　美紀", kana:"ウラタ", seat:"C-10"},
{no:8, cat:"特別来賓", org:"", title:"熊本県議会議長代理　熊本県議会議員", name:"池田　和貴", kana:"イケダ", seat:"C-9"},
{no:9, cat:"特別来賓", org:"", title:"熊本県議会議員", name:"楠本　千秋", kana:"クスモト", seat:"C-8"},
{no:10, cat:"特別来賓", org:"", title:"熊本県議会議員", name:"山口　裕", kana:"ヤマグチ", seat:"C-7"},
{no:11, cat:"県内市長及び議長", org:"", title:"熊本市副市長", name:"岡田　芳和", kana:"オカダ", seat:"C-21"},
{no:12, cat:"県内市長及び議長", org:"", title:"八代市副市長", name:"平井　宏英", kana:"ヒライ", seat:"C-22"},
{no:13, cat:"県内市長及び議長", org:"", title:"人吉市長", name:"松岡　隼人", kana:"マツオカ", seat:"C-23"},
{no:14, cat:"県内市長及び議長", org:"", title:"荒尾市副市長", name:"石川　陽一", kana:"イシカワ", seat:"C-24"},
{no:15, cat:"県内市長及び議長", org:"", title:"水俣市副市長", name:"緒方　雅一", kana:"オガタ", seat:"C-25"},
{no:16, cat:"県内市長及び議長", org:"", title:"玉名市副市長", name:"吉田　勇人", kana:"ヨシダ", seat:"D-14"},
{no:17, cat:"県内市長及び議長", org:"", title:"山鹿市副市長", name:"阿蘇品　貴司", kana:"アソシナ", seat:"D-15"},
{no:18, cat:"県内市長及び議長", org:"", title:"菊池市副市長", name:"藤井　一恵", kana:"フジイ", seat:"D-16"},
{no:19, cat:"県内市長及び議長", org:"", title:"宇土市長", name:"光井　正吾", kana:"ミツイ", seat:"D-17"},
{no:20, cat:"県内市長及び議長", org:"", title:"上天草市長", name:"堀江　隆臣", kana:"ホリエ", seat:"C-19"},
{no:21, cat:"県内市長及び議長", org:"", title:"宇城市副市長", name:"田村　真一", kana:"タムラ", seat:"D-18"},
{no:22, cat:"県内市長及び議長", org:"", title:"阿蘇市副市長", name:"沖　圭一郎", kana:"オキ", seat:"D-19"},
{no:23, cat:"県内市長及び議長", org:"", title:"合志市政策監", name:"吉村　幸一", kana:"ヨシムラ", seat:"D-20"},
{no:24, cat:"関係団体の首長及び議長", org:"", title:"産山村長", name:"井　雄一郎", kana:"イ", seat:"D-21"},
{no:25, cat:"関係団体の首長及び議長", org:"", title:"高森町長", name:"草村　大成", kana:"クサムラ", seat:"D-22"},
{no:26, cat:"関係団体の首長及び議長", org:"", title:"苓北町長", name:"山﨑　秀典", kana:"ヤマサキ", seat:"C-20"},
{no:27, cat:"関係団体の首長及び議長", org:"", title:"浦河町長", name:"松田　有宏", kana:"マツダ", seat:"D-23"},
{no:28, cat:"関係団体の首長及び議長", org:"", title:"瀬戸市副市長", name:"大森　雅之", kana:"オオモリ", seat:"D-24"},
{no:29, cat:"関係団体の首長及び議長", org:"", title:"南島原市副市長", name:"宮﨑　太", kana:"ミヤザキ", seat:"D-25"},
{no:30, cat:"関係団体の首長及び議長", org:"", title:"出水市長", name:"椎木　伸一", kana:"シイキ", seat:"D-26"},
{no:31, cat:"関係団体の首長及び議長", org:"", title:"長島町総務課長", name:"町口　真浩", kana:"マチグチ", seat:"D-27"},
{no:32, cat:"県内市長及び議長", org:"", title:"熊本市議会副議長", name:"井本　正広", kana:"イモト", seat:"D-10"},
{no:33, cat:"県内市長及び議長", org:"", title:"八代市議会議長", name:"髙山　正夫", kana:"タカヤマ", seat:"D-9"},
{no:34, cat:"県内市長及び議長", org:"", title:"人吉市議会議長", name:"宮原　将志", kana:"ミヤハラ", seat:"D-8"},
{no:35, cat:"県内市長及び議長", org:"", title:"荒尾市議会議長", name:"浜崎　英利", kana:"ハマサキ", seat:"D-7"},
{no:36, cat:"県内市長及び議長", org:"", title:"水俣市議会副議長", name:"田口　憲雄", kana:"タグチ", seat:"E-21"},
{no:37, cat:"県内市長及び議長", org:"", title:"玉名市議会議長", name:"西川　裕文", kana:"ニシカワ", seat:"E-20"},
{no:38, cat:"県内市長及び議長", org:"", title:"山鹿市議会議長", name:"有働　辰喜", kana:"ウドウ", seat:"E-19"},
{no:39, cat:"県内市長及び議長", org:"", title:"菊池市議会副議長", name:"泉田　栄一朗", kana:"イズミダ", seat:"E-18"},
{no:40, cat:"県内市長及び議長", org:"", title:"宇土市議会議長", name:"野口　修一", kana:"ノグチ", seat:"E-17"},
{no:41, cat:"県内市長及び議長", org:"", title:"上天草市議会議長", name:"嶋元　秀司", kana:"シマモト", seat:"D-12"},
{no:42, cat:"県内市長及び議長", org:"", title:"宇城市議会議長", name:"豊田　紀代美", kana:"トヨダ", seat:"E-16"},
{no:43, cat:"県内市長及び議長", org:"", title:"阿蘇市議会副議長", name:"谷﨑　利浩", kana:"タニザキ", seat:"E-15"},
{no:44, cat:"関係団体の首長及び議長", org:"", title:"産山村議会議長", name:"西澤　正", kana:"ニシザワ", seat:"E-14"},
{no:45, cat:"関係団体の首長及び議長", org:"", title:"高森町議会議長", name:"牛嶋　津世志", kana:"ウシジマ", seat:"E-13"},
{no:46, cat:"関係団体の首長及び議長", org:"", title:"苓北町議会議長", name:"野﨑　幸洋", kana:"ノザキ", seat:"D-11"},
{no:47, cat:"関係団体の首長及び議長", org:"", title:"浦河町議会議長", name:"米谷　友光", kana:"ヨネタニ", seat:"E-12"},
{no:48, cat:"関係団体の首長及び議長", org:"", title:"瀬戸市議会議長", name:"髙島　淳", kana:"タカシマ", seat:"E-11"},
{no:49, cat:"関係団体の首長及び議長", org:"", title:"雲仙市議会議長", name:"大久保　正美", kana:"オオクボ", seat:"E-10"},
{no:50, cat:"関係団体の首長及び議長", org:"", title:"出水市議会議長", name:"北御門　伸彦", kana:"キタミカド", seat:"E-9"},
{no:51, cat:"その他来賓", org:"", title:"天草市議会議長", name:"若山　敬介", kana:"ワカヤマ", seat:"C-2"},
{no:52, cat:"その他来賓", org:"", title:"天草市議会副議長", name:"小川　圭三", kana:"オガワ", seat:"D-5"},
{no:53, cat:"その他来賓", org:"", title:"天草市議会議員", name:"浜崎　昭臣", kana:"ハマサキ", seat:"D-4"},
{no:54, cat:"その他来賓", org:"", title:"天草市議会議員", name:"勝木　幸生", kana:"カツキ", seat:"D-3"},
{no:55, cat:"その他来賓", org:"", title:"天草市議会議員", name:"中尾　友二", kana:"ナカオ", seat:"D-2"},
{no:56, cat:"その他来賓", org:"", title:"天草市議会議員", name:"宮下　幸一郎", kana:"ミヤシタ", seat:"D-1"},
{no:57, cat:"その他来賓", org:"", title:"天草市議会議員", name:"濱洲　大心", kana:"ハマス", seat:"E-8"},
{no:58, cat:"その他来賓", org:"", title:"天草市議会議員", name:"柴田　誠", kana:"シバタ", seat:"E-7"},
{no:59, cat:"その他来賓", org:"", title:"天草市議会議員", name:"五通　俊作", kana:"ゴツウ", seat:"E-6"},
{no:60, cat:"その他来賓", org:"", title:"天草市議会議員", name:"五嶋　善彦", kana:"ゴトウ", seat:"E-5"},
{no:61, cat:"その他来賓", org:"", title:"天草市議会議員", name:"門口　徹", kana:"カドグチ", seat:"E-4"},
{no:62, cat:"その他来賓", org:"", title:"天草市議会議員", name:"澤井　一富", kana:"サワイ", seat:"E-3"},
{no:63, cat:"その他来賓", org:"", title:"天草市議会議員", name:"藤﨑　正博", kana:"フジサキ", seat:"E-2"},
{no:64, cat:"その他来賓", org:"", title:"天草市議会議員", name:"蓑田　庸子", kana:"ミノダ", seat:"E-1"},
{no:65, cat:"その他来賓", org:"", title:"天草市議会議員", name:"鯖江　達朗", kana:"サバエ", seat:"F-11"},
{no:66, cat:"その他来賓", org:"", title:"天草市議会議員", name:"松岡　寿", kana:"マツオカ", seat:"F-10"},
{no:67, cat:"その他来賓", org:"", title:"天草市議会議員", name:"浦本　力", kana:"ウラモト", seat:"F-9"},
{no:68, cat:"その他来賓", org:"", title:"天草市議会議員", name:"竹本　亨", kana:"タケモト", seat:"F-8"},
{no:69, cat:"その他来賓", org:"", title:"天草市議会議員", name:"赤城　史浩", kana:"アカギ", seat:"F-7"},
{no:70, cat:"その他来賓", org:"", title:"天草市議会議員", name:"栁田　光芳", kana:"ヤナギダ", seat:"F-6"},
{no:71, cat:"その他来賓", org:"", title:"天草市議会議員", name:"吉田　修", kana:"ヨシダ", seat:"F-5"},
{no:72, cat:"その他来賓", org:"", title:"天草市議会議員", name:"生嶋　祥子", kana:"イクシマ", seat:"F-4"},
{no:73, cat:"その他来賓", org:"", title:"天草市議会議員", name:"金子　馨", kana:"カネコ", seat:"F-3"},
{no:74, cat:"その他来賓", org:"", title:"天草市議会議員", name:"植田　貴俊", kana:"ウエダ", seat:"F-2"},
{no:75, cat:"その他来賓", org:"", title:"前天草市議会議員", name:"平山　泰司", kana:"ヒラヤマ", seat:"F-1"},
{no:76, cat:"その他来賓", org:"", title:"前天草市議会議員", name:"船辺　修", kana:"フナベ", seat:"G-12"},
{no:77, cat:"その他来賓", org:"", title:"前天草市議会議員", name:"鶴戸　継啓", kana:"ツルド", seat:"G-11"},
{no:78, cat:"その他来賓", org:"", title:"前天草市議会議員", name:"下田　昇一郎", kana:"シモダ", seat:"G-10"},
{no:79, cat:"その他来賓", org:"", title:"前天草市議会議員", name:"前田　正之", kana:"マエダ", seat:"G-9"},
{no:80, cat:"その他来賓", org:"", title:"前天草市副市長", name:"金子　邦彦", kana:"カネコ", seat:"G-8"},
{no:81, cat:"その他来賓", org:"", title:"前天草市教育長", name:"石井　二三男", kana:"イシイ", seat:"G-7"},
{no:82, cat:"その他来賓", org:"本渡まちづくり協議会", title:"会長", name:"中川　竹治", kana:"ナカガワ", seat:"H-12"},
{no:83, cat:"その他来賓", org:"牛深まちづくり協議会", title:"会長", name:"舩場　みちな", kana:"フナバ", seat:"H-11"},
{no:84, cat:"その他来賓", org:"御所浦まちづくり協議会", title:"会長", name:"森　啓輔", kana:"モリ", seat:"H-10"},
{no:85, cat:"その他来賓", org:"倉岳まちづくり協議会", title:"会長", name:"稲津　千明", kana:"イナヅ", seat:"H-9"},
{no:86, cat:"その他来賓", org:"栖本まちづくり協議会", title:"会長", name:"倉田　千尋", kana:"クラタ", seat:"H-8"},
{no:87, cat:"その他来賓", org:"五和まちづくり協議会", title:"会長", name:"井下　克也", kana:"イノシタ", seat:"H-7"},
{no:88, cat:"その他来賓", org:"天草まちづくり協議会", title:"会長", name:"嶋田　順一", kana:"シマダ", seat:"H-6"},
{no:89, cat:"その他来賓", org:"河浦まちづくり協議会", title:"会長", name:"野中　幸廣", kana:"ノナカ", seat:"H-5"},
{no:90, cat:"その他来賓", org:"本渡地域代表", title:"行政区長", name:"野口　俊夫", kana:"ノグチ", seat:"Z-"},
{no:91, cat:"その他来賓", org:"牛深地域代表", title:"行政区長", name:"井上　洋市", kana:"イノウエ", seat:"Z-"},
{no:92, cat:"その他来賓", org:"有明地域代表", title:"行政区長", name:"鏡　秀寿", kana:"カガミ", seat:"Z-"},
{no:93, cat:"その他来賓", org:"御所浦地域代表", title:"行政区長", name:"浦田　譲治", kana:"ウラタ", seat:"Z-"},
{no:94, cat:"その他来賓", org:"倉岳地域代表", title:"行政区長", name:"福原　徳長", kana:"フクハラ", seat:"Z-"},
{no:95, cat:"その他来賓", org:"栖本地域代表", title:"行政区長", name:"並﨑　一信", kana:"ナミザキ", seat:"Z-"},
{no:96, cat:"その他来賓", org:"新和地域代表", title:"行政区長", name:"中村　三千人", kana:"ナカムラ", seat:"Z-"},
{no:97, cat:"その他来賓", org:"五和地域代表", title:"行政区長", name:"田口　了一", kana:"タグチ", seat:"Z-"},
{no:98, cat:"その他来賓", org:"天草地域代表", title:"行政区長", name:"夏　一幸", kana:"ナツ", seat:"Z-"},
{no:99, cat:"その他来賓", org:"河浦地域代表", title:"行政区長", name:"登　和彦", kana:"ノボリ", seat:"Z-"},
{no:100, cat:"その他来賓", org:"", title:"天草市農業委員会会長", name:"山下　和弘", kana:"ヤマシタ", seat:"H-1"},
{no:101, cat:"その他来賓", org:"株式会社熊本県民テレビ天草通信部", title:"", name:"有江　武利", kana:"アリエ", seat:"J-22"},
{no:102, cat:"その他来賓", org:"天草ケーブルネットワーク株式会社", title:"代表取締役", name:"西村　正治", kana:"ニシムラ", seat:"J-21"},
{no:103, cat:"その他来賓", org:"天草教育事務所", title:"主幹兼指導課長", name:"中村　富男", kana:"ナカムラ", seat:"F-17"},
{no:104, cat:"その他来賓", org:"天草税務署", title:"署長", name:"永﨑　政継", kana:"ナガサキ", seat:"F-18"},
{no:105, cat:"その他来賓", org:"天草警察署", title:"署長", name:"堀　雅博", kana:"ホリ", seat:"F-19"},
{no:106, cat:"その他来賓", org:"牛深警察署", title:"署長", name:"森田　卓巳", kana:"モリタ", seat:"F-20"},
{no:107, cat:"その他来賓", org:"天草広域連合消防本部", title:"消防長", name:"戸村　羊士", kana:"トムラ", seat:"F-21"},
{no:108, cat:"その他来賓", org:"天草海上保安署", title:"署長", name:"金棒　康彦", kana:"カナボウ", seat:"F-22"},
{no:109, cat:"その他来賓", org:"厚生労働省熊本労働局天草労働基準監督署", title:"署長", name:"嘉悦　正人", kana:"カエツ", seat:"F-23"},
{no:110, cat:"その他来賓", org:"日本年金機構本渡年金事務所", title:"所長", name:"長谷川　健一", kana:"ハセガワ", seat:"F-15"},
{no:111, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"池崎　教授", kana:"イケザキ", seat:"G-1"},
{no:112, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"行合　八恵子", kana:"ユキアイ", seat:"G-2"},
{no:113, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"木下　えり子", kana:"キノシタ", seat:"G-3"},
{no:114, cat:"その他来賓", org:"天草市教育委員会", title:"委員", name:"小林　景子", kana:"コバヤシ", seat:"G-4"},
{no:115, cat:"その他来賓", org:"天草市選挙管理委員会", title:"委員長", name:"岡部　義夫", kana:"オカベ", seat:"H-2"},
{no:116, cat:"その他来賓", org:"天草市監査委員", title:"", name:"富田　善三郎", kana:"トミタ", seat:"G-6"},
{no:117, cat:"その他来賓", org:"天草市監査委員", title:"", name:"福岡　耕二", kana:"フクオカ", seat:"G-5"},
{no:118, cat:"その他来賓", org:"熊本県市町村職員年金者連盟天草支部", title:"支部長", name:"冨安　英猛", kana:"トミヤス", seat:"F-16"},
{no:119, cat:"その他来賓", org:"天草市民生委員児童委員協議会連合会", title:"会長", name:"濱田　幸人", kana:"ハマダ", seat:"G-13"},
{no:120, cat:"その他来賓", org:"社会福祉法人天草市社会福祉協議会", title:"事務局長", name:"小浦　良介", kana:"コウラ", seat:"G-14"},
{no:121, cat:"その他来賓", org:"天草市身体障害者福祉協議会", title:"会長", name:"松本　若津", kana:"マツモト", seat:"I-13"},
{no:122, cat:"その他来賓", org:"天草市視力障害者福祉協会", title:"会長", name:"大塚　聖子", kana:"オオツカ", seat:"I-14"},
{no:123, cat:"その他来賓", org:"白い雲の会", title:"会長", name:"堤田　照一", kana:"ツツミダ", seat:"I-15"},
{no:124, cat:"その他来賓", org:"精神保健福祉会天草地域家族会", title:"事務局長", name:"池崎　宏一", kana:"イケザキ", seat:"I-16"},
{no:125, cat:"その他来賓", org:"天草市保育所連盟", title:"会長", name:"安田　量寛", kana:"ヤスダ", seat:"I-17"},
{no:126, cat:"その他来賓", org:"天草市老人クラブ連合会", title:"会長", name:"早水　英雄", kana:"ハヤミズ", seat:"H-13"},
{no:127, cat:"その他来賓", org:"公益社団法人天草市シルバー人材センター", title:"理事長", name:"江﨑　和男", kana:"エザキ", seat:"H-14"},
{no:128, cat:"その他来賓", org:"一般社団法人天草郡市医師会", title:"会長", name:"東　一成", kana:"ヒガシ", seat:"I-20"},
{no:129, cat:"その他来賓", org:"一般社団法人天草郡市薬剤師会", title:"副会長", name:"草積　里恵子", kana:"クサヅミ", seat:"I-21"},
{no:130, cat:"その他来賓", org:"熊本県獣医師会天草支部", title:"支部長", name:"奈良﨑　孝一郎", kana:"ナラザキ", seat:"I-22"},
{no:131, cat:"その他来賓", org:"子宝島あまくさ助産師会", title:"会長", name:"池田　眞智子", kana:"イケダ", seat:"I-23"},
{no:132, cat:"その他来賓", org:"天草市食生活改善推進員協議会", title:"会長", name:"風間　泰民子", kana:"カザマ", seat:"J-15"},
{no:133, cat:"その他来賓", org:"あまくさ農業協同組合", title:"代表理事組合長", name:"﨑本　和人", kana:"サキモト", seat:"G-17"},
{no:134, cat:"その他来賓", org:"本渡五和農業協同組合", title:"代表理事組合長", name:"吉田　誠", kana:"ヨシダ", seat:"G-18"},
{no:135, cat:"その他来賓", org:"熊本県畜産農業協同組合天草支所", title:"運営委員長", name:"千原　勝也", kana:"チハラ", seat:"G-19"},
{no:136, cat:"その他来賓", org:"熊本県農業共済組合天草支所", title:"支所長", name:"宮崎　浩司", kana:"ミヤザキ", seat:"G-20"},
{no:137, cat:"その他来賓", org:"地方卸売市場本渡青果事業協同組合", title:"理事長", name:"濱　三千秀", kana:"ハマ", seat:"G-21"},
{no:138, cat:"その他来賓", org:"天草地域森林組合", title:"代表理事専務", name:"野嶋　義澄", kana:"ノジマ", seat:"G-22"},
{no:139, cat:"その他来賓", org:"天草漁業協同組合", title:"副組合長理事", name:"渕口　文俊", kana:"フチグチ", seat:"G-23"},
{no:140, cat:"その他来賓", org:"熊本県海水養殖漁業協同組合", title:"代表理事組合長", name:"深川　英穂", kana:"フカガワ", seat:"G-24"},
{no:141, cat:"その他来賓", org:"熊本大分真珠養殖漁業協同組合", title:"代表理事組合長", name:"田畑　圭規", kana:"タバタ", seat:"H-21"},
{no:142, cat:"その他来賓", org:"倉岳町漁業協同組合", title:"代表理事組合長", name:"蛭子本　臣偵", kana:"エビスモト", seat:"H-22"},
{no:143, cat:"その他来賓", org:"御所浦町漁業協同組合", title:"代表理事組合長", name:"脇島　成郎", kana:"ワキシマ", seat:"H-23"},
{no:144, cat:"その他来賓", org:"栖本漁業協同組合", title:"代表理事組合長", name:"倉本　雄市", kana:"クラモト", seat:"H-24"},
{no:145, cat:"その他来賓", org:"天草たばこ販売協同組合", title:"理事", name:"山川　智己", kana:"ヤマカワ", seat:"I-24"},
{no:146, cat:"その他来賓", org:"一般社団法人熊本県天草地区建設業協会", title:"理事長", name:"松下　眞一", kana:"マツシタ", seat:"I-2"},
{no:147, cat:"その他来賓", org:"熊本県建築士会天草支部", title:"支部長", name:"岩﨑　良弘", kana:"イワサキ", seat:"I-3"},
{no:148, cat:"その他来賓", org:"天草市建友会", title:"副会長", name:"福富　崇司", kana:"フクトミ", seat:"I-1"},
{no:149, cat:"その他来賓", org:"天草経済開発同友会", title:"会長", name:"野上　俊樹", kana:"ノガミ", seat:"G-16"},
{no:150, cat:"その他来賓", org:"一般社団法人天草宝島観光協会", title:"会長", name:"山下　修平", kana:"ヤマシタ", seat:"J-7"},
{no:151, cat:"その他来賓", org:"本渡飲食業組合", title:"組合長", name:"田口　博典", kana:"タグチ　ヒロノリ", seat:"J-6"},
{no:152, cat:"その他来賓", org:"天草市社交飲食業組合", title:"組合長", name:"石井　美恵", kana:"イシイ　ミエ", seat:"J-5"},
{no:153, cat:"その他来賓", org:"天草ほんど観光旅館ホテル組合", title:"組合長", name:"横島　龍一", kana:"ヨコシマ　リュウイチ", seat:"J-4"},
{no:154, cat:"その他来賓", org:"有明町旅館組合", title:"組合長", name:"松本　國雄", kana:"マツモト　クニオ", seat:"J-2"},
{no:155, cat:"その他来賓", org:"下田温泉旅館組合", title:"組合長", name:"藤本　貴士", kana:"フジモト　タカシ", seat:"J-3"},
{no:156, cat:"その他来賓", org:"天草宝島案内人の会", title:"会長", name:"金澤　裕巖", kana:"カナザワ　ユウガン", seat:"Z-"},
{no:157, cat:"その他来賓", org:"天草女将の会", title:"", name:"松本　鈴子", kana:"マツモト　スズコ", seat:"J-1"},
{no:158, cat:"その他来賓", org:"天草市小中学校長会", title:"会長", name:"松原　康近", kana:"マツバラ　ヤスチカ", seat:"J-18"},
{no:159, cat:"その他来賓", org:"天草市ＰＴＡ連絡協議会", title:"会長", name:"松本　大器", kana:"マツモト　ダイキ", seat:"J-17"},
{no:160, cat:"その他来賓", org:"天草市地域婦人会連絡協議会", title:"会長", name:"木崎　眞美子", kana:"キザキ　マミコ", seat:"J-14"},
{no:161, cat:"その他来賓", org:"天草市子ども会育成連絡協議会", title:"会長", name:"島﨑　太", kana:"シマザキ", seat:"J-16"},
{no:162, cat:"その他来賓", org:"天草市男女共同参画推進ネットワーク　つんのでネット～風～", title:"事務局", name:"益田　靖子", kana:"マスダ", seat:"J-13"},
{no:163, cat:"その他来賓", org:"一般社団法人　市民活動サポートあまみん", title:"代表理事", name:"山本　智保子", kana:"ヤマモト", seat:"J-12"},
{no:164, cat:"その他来賓", org:"一般社団法人天草市スポーツ協会", title:"会長", name:"江浦　むつえ", kana:"エウラ", seat:"J-11"},
{no:165, cat:"その他来賓", org:"天草市スポーツ推進委員協議会", title:"会長", name:"渡邊　亨", kana:"ワタナベ", seat:"J-10"},
{no:166, cat:"その他来賓", org:"天草文化協会", title:"副会長", name:"嶺　力", kana:"ミネ", seat:"J-9"},
{no:167, cat:"その他来賓", org:"一般社団法人天草市芸術文化協会", title:"会長", name:"江﨑　俊一", kana:"エサキ", seat:"J-8"},
{no:168, cat:"その他来賓", org:"熊本検察審査協会天草支部", title:"支部長", name:"落合　正実", kana:"オチアイ", seat:"H-4"},
{no:169, cat:"その他来賓", org:"天草人権擁護委員協議会", title:"会長", name:"貴田　英広", kana:"キダ", seat:"I-12"},
{no:170, cat:"その他来賓", org:"天草地区保護司会", title:"会長", name:"出田　豪", kana:"イズタ", seat:"I-11"},
{no:171, cat:"その他来賓", org:"天草市自衛隊家族会", title:"会長", name:"若山　幸信", kana:"ワカヤマ", seat:"I-10"},
{no:172, cat:"その他来賓", org:"天草地区交通安全協会", title:"会長", name:"田中　靖士", kana:"タナカ", seat:"I-9"},
{no:173, cat:"その他来賓", org:"牛深地区交通安全協会", title:"会長", name:"中村　富人", kana:"ナカムラ", seat:"I-8"},
{no:174, cat:"その他来賓", org:"天草市交通指導員会", title:"隊長", name:"尾下　明", kana:"オシタ", seat:"I-7"},
{no:175, cat:"その他来賓", org:"牛深地区安全運転管理者等協議会", title:"会長", name:"福岡　英人", kana:"フクオカ", seat:"I-6"},
{no:176, cat:"その他来賓", org:"天草警察署沿岸警備協力会", title:"会長", name:"北　武敏", kana:"キタ", seat:"I-5"},
{no:177, cat:"その他来賓", org:"牛深警察署沿岸警備協力会", title:"会長", name:"杦本　幸徳", kana:"スギモト", seat:"I-4"},
{no:178, cat:"その他来賓", org:"天草市消防団", title:"団長", name:"田中　浩介", kana:"タナカ", seat:"H-3"},
{no:179, cat:"その他来賓", org:"本渡商工会議所", title:"会頭", name:"金子　勉", kana:"カネコ", seat:"F-14"},
{no:180, cat:"その他来賓", org:"牛深商工会議所", title:"会頭", name:"益田　政昭", kana:"マスダ", seat:"F-13"},
{no:181, cat:"その他来賓", org:"天草市商工会", title:"会長", name:"古賀　源一郎", kana:"コガ", seat:"F-12"},
{no:182, cat:"その他来賓", org:"公益社団法人天草法人会", title:"会長", name:"永田　章一", kana:"ナガタ", seat:"G-15"},
{no:183, cat:"その他来賓", org:"一般社団法人天草本渡青年会議所", title:"理事長", name:"大中　龍", kana:"オオナカ", seat:"H-20"},
{no:184, cat:"その他来賓", org:"天草食品衛生協会", title:"会長", name:"堀田　征夫", kana:"ホッタ", seat:"H-19"},
{no:185, cat:"その他来賓", org:"天草ロータリークラブ", title:"会長", name:"小島　竜二", kana:"コジマ", seat:"H-18"},
{no:186, cat:"その他来賓", org:"天草中央ロータリークラブ", title:"会長", name:"山川　悟", kana:"ヤマカワ", seat:"H-17"},
{no:187, cat:"その他来賓", org:"牛深ロータリークラブ", title:"会長", name:"山下　修平", kana:"ヤマシタ", seat:"H-16"},
{no:188, cat:"その他来賓", org:"天草本渡ライオンズクラブ", title:"会長", name:"岩﨑　東洋司", kana:"イワサキ", seat:"H-15"},
{no:189, cat:"その他来賓", org:"ゼロ―ム天草", title:"新事業推進委員長", name:"木原　潤", kana:"キハラ", seat:"J-19"},
{no:190, cat:"その他来賓", org:"天草エアライン株式会社", title:"代表取締役社長", name:"山西　聡", kana:"ヤマニシ", seat:"J-20"},

];
